# FOR inference
FROM python:3.10-bullseye

# copy and install dependencies from requirements.txt
RUN pip install --upgrade pip setuptools wheel
COPY requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt
RUN mkdir -p /models

# copy the app.
COPY . /app
RUN chmod +x /app/docker/entrypoint.sh
ENTRYPOINT ["/app/docker/entrypoint.sh"]
