# FOR inference
FROM resdsql-base

RUN mkdir -p /data/custom/database && chmod -R 777 /data/custom/database
RUN chmod +x /app/docker/entrypoint.sh
EXPOSE 8000
ENTRYPOINT ["/app/docker/entrypoint.sh"]
